### ISSUE TITLE
Things that need to happen in order for the server to get fixed

### ISSUE THREAD

**Issue by dovis-gif** [dniym/Bending#26]
-removed irrelevant ranting-

**Set the server's render distance to default.**
The server's render distance of a mere 3 chunks/50 blocks (compared to the default 10 chunks/160 blocks). This would be annoying in any case, but it's especially terrible for a bending server. In bending PVP, players move at an incredibly fast pace because of all their mobility moves (airblast, firejet, etc). This means that the player will constantly disappear in a PVP match, which makes PVP effectively impossible. We should have a much higher render distance, just like every other bending server in existence. If this causes lag, then there's a problem with the server. Perhaps it needs more RAM, or perhaps the developers of PK have optimized their plugin since it was last installed and subsequently forked into Megabending. 

**Install the OldCombatMechanics plugin**
Minecraft's regen/hunger mechanics were tweaked by the Combat update. Regen is incredibly fast, but only when your food bars are full. Since food and saturation depletes rapidly, regen is effectively abolished. This might be useful for vanilla PVP where duels can last seconds, but it is incompatible with bending PVP, because matches tend to last much longer, and the bending arena (keep in mind that the arena is the main reason why people join a bending server) is supposed to be a place where you don't need to worry about hunger. All of this can be solved by installing the OldCombatMechanics plugin. PVP with no regen might be a fun minigame, but it makes the main gameplay impossible.

**Install the latest versions of ProjectKorra and Jedcore**
I don't think that you even realize how broken the server is. _I don't even realize how broken the server is, because I've only tested fire_. You seem to be under the impression that we can fix the server by patching a few bugs here and there. I don't even know what version of PK and Jedcore we're using (before it forked into Megabending), but I assume that it is ancient. So we're running an ancient, suboptimal plugin, which becomes buggier and buggier with each successive Mojang update.
And it usually takes the developers of PK months before they put out a new update, and the updates are not strictly limited to adjusting the plugin to the latest version of Minecraft. And they have a helluva lot more developers and testers than we do.  And it seems that every time we patch a bug, new bugs are created to replace it. How many times have I reported bugs on firejet, only to find new bugs immediately after (Jetblast and Jetblaze are still broken BTW)? And this is only fire, not even including the other elements!
So, realistically speaking, the project that you're trying to pursue is completely pointless. You cannot manually update the entire PK and Jedcore, especially since you don't even know how these moves are supposed to function (even I don't, I only know fire.) So the project is a fantasy. It is a complete waste of everyone's time, including your own, because it's going nowhere. It is heading towards a dead end.
**Therefore**, we need to install the latest versions of PK and Jedcore, with everything set to default (at least for now). Custom moves should be rewritten or replaced by new ones (I can help you with ideas). I think this would be easier for you, since you're more intimately familiar with your own moves since you yourself designed them. You know exactly what they're supposed to look like and how they're supposed to function. If you had done this from the beginning, bending arguably could have been fixed by now.

-more irrelevant rambling-

There are many other issues with the server, but these are the biggest ones. They make it absolutely impossible to play. If these issues are addressed, then we can proceed to talk about other issues with the server (and there are many). But if dniym doesn't cooperate, then I quit. I can't help you if you refuse to take my help. If you stubbornly insist that you can fix the server with all of these limitations, then you can go right ahead. But I don't see it as a worthy investment of my time.

**Comment by dniym** [comment]
Yet again you cannot follow directions.   ONE ISSUE / SUGGESTION PER POST we have gone over this over and over and you either don’t care or can’t comprehend simple instructions.   But just this once I’ll respond to this post in the same horrific manner


1) SERVERS RENDER DISTANCE IN THE CONFIG IS SET TO DEFAULT.  IT HAS NOT BEEN LOWERED FROM THE DEFAULT SPIGOT SETTING.  I WILL INCREASE IT AND IF IT CAUSES ISSUES IT WILL BE LOWERED.   INCREASING THE RENDER DISTANCE FOR EXACTLY ONE MOVE THAT HAS A 100 RANGE IS IDIOTIC.   

2) WHEN COMBAT TAGGED ALL REGEN IS DISABLED, THIS GOES FOR THE ARENA AND THE PLAYABLE WORLD IF THIS NEEDS TO BE ADJUSTED OR IF THERE IS SOMETHING LACKING PLEASE OPEN A NEW SUGGESTION ABOUT ONLY THIS TOPIC.  

3) THE LAST TIME WE DID THIS IT WAS MET WITH NOTHING BUT COMPLAINTS INCLUDING FROM YOU, PROJECTKORRA LACKS A LOT OF THINGS THAT WE HAVE HERE, FURTHERMORE WE DO NOT EVEN USE JEDCORE, ITS AN ABANDONED PROJECT THAT IS ONLY MAINTAINED. IT DOES NOT FOLLOW THE STANDARDS SET FORTH BY THE PROJECTKORRA AUTHORS AT ALL AND CAUSES TONS OF ISSUES ALL BY ITSELF. 

4) DAVID / DOVI NEEDS TO STOP TAKING ANY COMMENT OR OPINION THAT DIFFERS FROM HIS AS A DIRECT PERSONAL ATTACK. HE ALSO NEEDS TO LEARN HOW TO COMMUNICATE WITH OTHERS.   YOU DO ANNOY THE PISS OUT OF EVERYONE YOU TALK TO NOT JUST DNIYM, YOU REFUSES TO FOLLOW SIMPLE DIRECTIONS WHICH MAKES EVEN TRYING TO READ A SUGGESTION OR BUG REPORT SUBMITTED FROM YOU A CHORE.  

Now I’ve responded and I had questions since this is all crammed together in one post instead of separate issues nobody can follow this post and keep track of it, nor can it be closed marked as fixed or anything else because there are valid points but there are also parts of it that need more discussion.  


Edit just saw another thing, you’re apparently also reporting a new bug with jet blast / jet blaze here which is a suggestion thread, this is again the wrong place to do that.  Your last bug report said they didn’t function at all, that was fixed.  If there’s a new issue please open a new bug report for the new issue.

**Comment by dniym** [comment]
Closing issue because op can not / will not follow directions.
